server:
  port: 8191
spring:
  cloud:
    config:
      server:
        git:
#          uri: file://opt/PROJECT/sample/microservices/config-store
          uri: https://github.com/rowi-dev/config-store
#          uri: https://github.com/krish/microservices-course-on-youtube-config-store
#          search-paths:
#            - '*'
#spring:
#  profiles:
#    active: native
